<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>e_commerce.app</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\e-commerce.core\e-commerce.core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="12.0.0" />
		<PackageReference Include="FluentValidation" Version="8.0.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
		<PackageReference Include="MailKit" Version="4.15.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
		<PackageReference Include="MimeKit" Version="4.15.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
	</ItemGroup>

</Project>
